/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
 
#ifndef OP_API_OP_API_COMMON_INC_OPDEV_OP_ERRNO_H
#define OP_API_OP_API_COMMON_INC_OPDEV_OP_ERRNO_H

#define ACLNN_SUCCESS 0
#define ACLNN_ERR_PARAM_NULLPTR 161001
#define ACLNN_ERR_PARAM_INVALID 161002
#define ACLNN_ERR_RUNTIME_ERROR 361001
#define ACLNN_ERR_INNER 561000
#define ACLNN_ERR_INNER_INFERSHAPE_ERROR 561001
#define ACLNN_ERR_INNER_TILING_ERROR 561002
#define ACLNN_ERR_INNER_FIND_KERNEL_ERROR 561003
#define ACLNN_ERR_INNER_CREATE_EXECUTOR 561101
#define ACLNN_ERR_INNER_NOT_TRANS_EXECUTOR 561102
#define ACLNN_ERR_INNER_NULLPTR 561103
#define ACLNN_ERR_INNER_WRONG_ATTR_INFO_SIZE 561104
#define ACLNN_ERR_INNER_KEY_CONFILICT 561105
#define ACLNN_ERR_INNER_INVALID_IMPL_MODE 561106
#define ACLNN_ERR_INNER_OPP_PATH_NOT_FOUND 561107
#define ACLNN_ERR_INNER_LOAD_JSON_FAILED 561108
#define ACLNN_ERR_INNER_JSON_VALUE_NOT_FOUND 561109
#define ACLNN_ERR_INNER_JSON_FORMAT_INVALID 561110
#define ACLNN_ERR_INNER_JSON_DTYPE_INVALID 561111
#define ACLNN_ERR_INNER_OPP_KERNEL_PKG_NOT_FOUND 561112

#define ACLNN_ERR_INNER_OP_FILE_INVALID 561113
#define ACLNN_ERR_INNER_ATTR_NUM_OUT_OF_BOUND 561114
#define ACLNN_ERR_INNER_ATTR_LEN_NOT_ENOUGH 561115
#define ACLNN_ERR_INNER_INPUT_NUM_IN_JSON_TOO_LARGE 561116
#define ACLNN_ERR_INNER_INPUT_JSON_IS_NULL 561117
#define ACLNN_ERR_INNER_STATIC_WORKSPACE_INVALID 561118
#define ACLNN_ERR_INNER_STATIC_BLOCK_DIM_INVALID 561119

#endif // OP_API_OP_API_COMMON_INC_OPDEV_OP_ERRNO_H
